# Generated by Django 4.2 on 2023-05-08 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Blogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_author", models.CharField(max_length=40)),
                ("blog_heading", models.CharField(max_length=100)),
                ("blog_text", models.TextField()),
                ("blog_posted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=200)),
                ("categorie_des", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Distributor_Applicants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_state_name", models.CharField(max_length=100)),
                ("applicant_district_name", models.CharField(max_length=100)),
                ("applicant_tulka", models.CharField(max_length=100)),
                ("personal_name", models.CharField(max_length=40)),
                ("personal_age", models.IntegerField()),
                ("personal_address", models.CharField(max_length=200)),
                ("personal_pincode", models.CharField(max_length=7)),
                ("personal_companyname", models.CharField(max_length=150)),
                ("personal_mobile", models.CharField(max_length=12)),
                ("personal_alt_mobile", models.CharField(blank=True, max_length=12)),
                ("personal_telephone", models.CharField(blank=True, max_length=12)),
                ("personal_email", models.EmailField(max_length=254)),
                ("personal_educational_details", models.TextField()),
                ("partner_name", models.CharField(max_length=40)),
                ("partner_address", models.CharField(max_length=200)),
                ("partner_pincode", models.CharField(max_length=7)),
                ("partner_mobile", models.CharField(max_length=12)),
                ("partner_alt_mobile", models.CharField(blank=True, max_length=12)),
                ("partner_telephone", models.CharField(blank=True, max_length=12)),
                ("partner_email", models.EmailField(max_length=254)),
                ("applicant_experience", models.TextField()),
                ("applicant_storage_check", models.BooleanField()),
                ("applicant_storage_info", models.IntegerField(blank=True, null=True)),
                ("applicant_transport_check", models.BooleanField()),
                (
                    "applicant_transport_info",
                    models.CharField(blank=True, max_length=200),
                ),
                ("applicant_invesment_capacity", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User_distributor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_companyname", models.CharField(max_length=150)),
                ("user_mobile", models.CharField(max_length=12)),
                ("user_address", models.CharField(max_length=200)),
                ("user_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_description", models.TextField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "categorie_prod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.categorie"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="distributor_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.user_distributor"
            ),
        ),
    ]
