# Generated by Django 4.2 on 2023-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorie",
            name="catg_img",
            field=models.ImageField(default="eye.jpg", upload_to="catg/"),
        ),
        migrations.AddField(
            model_name="product",
            name="prod_img",
            field=models.ImageField(default="eye.jpg", upload_to="prod/"),
        ),
    ]
