# Generated by Django 4.2 on 2023-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_categorie_catg_img_product_prod_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gal_img", models.ImageField(upload_to="gall/")),
            ],
        ),
    ]
