# Generated by Django 4.2 on 2023-05-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_gallery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distributor_applicants",
            name="applicant_storage_check",
        ),
        migrations.RemoveField(
            model_name="distributor_applicants",
            name="applicant_transport_check",
        ),
        migrations.AlterField(
            model_name="distributor_applicants",
            name="applicant_storage_info",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
