# Generated by Django 4.2 on 2023-05-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_rename_ticket_complain_ticket_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_closed",
            field=models.BooleanField(default=False),
        ),
    ]
