# Generated by Django 4.1.5 on 2023-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_order_order_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='Unit',
            field=models.CharField(choices=[('Bag', 'Bag'), ('Gram', 'Gram'), ('Kg', 'Kg')], max_length=10, null=True),
        ),
    ]
