# Generated by Django 4.1.5 on 2023-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_orderitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='Unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
